### ISSUE TITLE
https://github.com/njones/socketio/milestones

### ISSUE THREAD

**Issue by LETHOTHIEN** [njones/socketio#2]
[https://github.com/njones/socketio/milestones]()

**Comment by njones** [comment]
Hi @LETHOTHIEN ... Thanks for leaving an issue. I'm not sure what you're looking to fix with this... can you add more context?

**Comment by LETHOTHIEN** [comment]
Thank

**Comment by LETHOTHIEN** [comment]
Tôi rất cảm ơn . Và sẽ cố gắng. Tôi cần nhà đầu tư để tôi được học hỏi

**Comment by LETHOTHIEN** [comment]
Tôi hiện tại,đang theo học chứng khoán, tôi cô gắng đầu tư, nhưng chưa đủ số vốn 10$ rất hy vọng có nhà đầu tư, hảo tâm,tiếp sức tôi
