### ISSUE TITLE
Update ReadMe Example

### ISSUE THREAD

**Issue by eli-rich** [njones/socketio#45]
This project looks really cool!
But the usage is not clear. The readme example does not compile. Even after adjusting it I could not get the server to run.

**Comment by njones** [comment]
Hi @BlazingFire007 sorry, you couldn't get the example in the README to work. Let me see if I can update things to be clearer.

**Comment by nmilallos97** [comment]
Hello! This project is really promising... I would like to ask if there is a way to leave a room?
