### ISSUE TITLE
Latest version at main branch doesn't allow clients to connect to multiple namespaces

### ISSUE THREAD

**Issue by tavancini-tc** [njones/socketio#60]
Latest version at the main branch (12ccfd1acb7b5610f89e980a3385bb1a0cd2a43b) doesn't allow clients to connect to multiple namespaces.

To reproduce:

**Client (Python):**

requirements.txt
```txt
python-socketio
python-socketio[client]==4.6.1
```

main.py
```python
import socketio

NAMESPACES = ["/channel"]
URL = "http://127.0.0.1:8003/"

sio = socketio.Client(logger=True, engineio_logger=True)

@sio.event
def connect():
    print('connection established')

@sio.event
def connect_error(data):
    print("The connection failed!")

@sio.event
def disconnect():
    print('disconnected from server')

sio.connect(URL,
    transports="websocket",
    namespaces=NAMESPACES)

sio.wait()
```

**Server:**

main.go
```go
package main

import (
	"log"
	"net/http"
	"time"

	sio "github.com/njones/socketio"
	eio "github.com/njones/socketio/engineio"
	eiot "github.com/njones/socketio/engineio/transport"
)

func main() {
	port := "localhost:8003"

	server := sio.NewServerV2(
		eio.WithSessionShave(1*time.Millisecond),
		eio.WithPingInterval(5*time.Second),
		eio.WithPingTimeout(1*time.Minute),
		eio.WithMaxPayload(1000000),
		eio.WithTransportOption(eiot.WithGovernor(1500*time.Microsecond, 500*time.Microsecond)),
	)

	// Root namespace
	server.OnConnect(func(socket *sio.SocketV2) error {
		log.Printf("/ %s connected.", socket.ID().String())
		return nil
	})

	// Channel namespace
	channel := server.Of("/channel")
	channel.OnConnect(func(socket *sio.SocketV2) error {
		log.Printf("/channel %s connected.", socket.ID().String())
		return nil
	})

	log.Printf("Serving port %s...\n", port)
	log.Fatal(http.ListenAndServe(port, server))
}
```

If you use v0.1.1 --  `go get github.com/njones/socketio@v0.1.1`, it works, it connects to "/" and "/channel".
But if you use the latest version -- `go get github.com/njones/socketio@main`, it doesn't work, it just connects to "/".

Let me know if you need anything else. Keep up the great work!

**Comment by njones** [comment]
Thanks for report, I'll look into this. If I have any more questions I'll ping this thread.

**Comment by njones** [comment]
Okay, I've found where the issue is. I should have a test and the fix out in about a day.

**Comment by njones** [comment]
This should be working, now. Thank you for the detailed bug report. It helped in fixing the bug.

**Comment by tavancini-tc** [comment]
Glad to help! I'll keep testing the lib in the next few days, if I find anything else I'll let you know. Thanks!

**Comment by tavancini-tc** [comment]
Hey Nika, I tried to send a message to "/channel" and it says that /channel is not a connected namespace.
