### ISSUE TITLE
On callback return map[string]interface{} empty

### ISSUE THREAD

**Issue by mmavka** [njones/socketio#66]
Hello. Thanks for the library
I can't sort out the callback for On (subscription events). In server. I received empty map[string]interface. 
Can you help me this problem, maybe. thanks

I sending test message from Postman as JSON. Setting v4 or v3

<details>
  <summary>Message</summary>

  ```
{
    "key": "value" 
}
  ```
</details>

<details>
  <summary>Use code map</summary>

  ```
  server.On("event", callback.Wrap{
		Parameters: []ser.Serializable{ser.MapParam},
		Func: func() interface{} {
			return func(msg map[string]interface{}) error {
				fmt.Println(msg)
				return nil
			}
		},
	})
  ```
</details>

I getting empty map. map[]

if I set StrParam

<details>
  <summary>Use code string</summary>

  ```
  server.On("event", callback.Wrap{
		Parameters: []ser.Serializable{ser. StrParam},
		Func: func() interface{} {
			return func(msg string) error {
				fmt.Println(msg)
				return nil
			}
		},
	})
  ```
</details>

then I getting string "map[key:value]"

**Comment by njones** [comment]
Hi mmavka,

Thanks for using the library! The `callback.Wrap` struct is supposed to be used for simple things, so it was only set to use reflection on scalar values, but a map seemed logical and easy to add. So I added it, and updated the examples with it. Also I updated examples on how to add a map as a custom callback, that's how you can do complex objects. You can see the examples [linked here](https://github.com/njones/socketio/blob/206fb29ff58f90e6351e1b0ebacb993246563330/callback/callback_test.go).

**Comment by njones** [comment]
The updated examples link is [here](https://github.com/njones/socketio/blob/ea3948c783fbba66a7b2100e43695c158e1d52ce/callback/callback_test.go).

**Comment by mmavka** [comment]
Thanks
